apiVersion: v1
kind: Pod

metadata:
  name: demo-api-pod
  labels:
    app: demo-api

spec:
  containers:
    - name: demo-api
      image: saurabhj25/k8s-docker-playground:2.0
      ports:
        - containerPort: 3000